on:
  workflow_dispatch:
    inputs:
      OPENFGA_IMAGE:
        type: string
        default: openfga/openfga
        required: true
      OPENFGA_IMAGE_TAG:
        type: string
        required: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            OPENFGA_IMAGE=${{ github.event.inputs.OPENFGA_IMAGE }}
            OPENFGA_IMAGE_TAG=${{ github.event.inputs.OPENFGA_IMAGE_TAG }}
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.event.inputs.OPENFGA_IMAGE_TAG }}
